/*
 * Ephemeral per-project store (ADR-005, storage backend per ADR-008). Each
 * project lives under "<slug>/" in the storage driver — book.json + meta.json
 * + assets/ — on local disk in dev (data/projects/) or in Netlify Blobs when
 * deployed. Projects expire after an idle TTL; the sweep runs opportunistically
 * from the project API routes.
 *
 * Server-only. All slugs and relative paths are validated here, before they
 * become storage keys — the single traversal guard for the project tree.
 */
import type { Book } from "./book-schema";
import { CURRENT_SCHEMA_VERSION, DEFAULT_PAGE_CONFIG } from "./book-schema";
import { migrateBook } from "./book-migrate";
import { storage } from "./storage";

// Idle TTL before a project is swept. Default is 1 day (1440 min); override
// with GUIDED_PROJECT_TTL_MIN if a deployment wants a different window.
export const PROJECT_TTL_MS =
  Number(process.env.GUIDED_PROJECT_TTL_MIN ?? 1440) * 60 * 1000;

/** Slugs that must never be assigned to a user project. */
export const RESERVED_SLUGS = new Set([
  "demo",
  "quickstart",
  "terms",
  "privacy",
  "api",
  "assets",
  "print",
  "new",
  "_next",
]);

export interface ProjectMeta {
  slug: string;
  name: string;
  createdAt: number;
  updatedAt: number;
}

/** Base slug from a project name: lowercase, non-alphanumerics → hyphens. */
export function baseSlug(name: string): string {
  const s = name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-")
    .slice(0, 60);
  return s || "project";
}

/*
 * Slugs are only generated by baseSlug/uniqueSlug (lowercase alphanumerics and
 * inner hyphens) but arrive back over the wire as URL params, so every store
 * entry point re-validates before the slug becomes a storage key.
 */
const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,78}$/;

export function isValidSlug(slug: string): boolean {
  return SLUG_RE.test(slug);
}

const projectPrefix = (slug: string) => {
  if (!isValidSlug(slug)) throw new Error(`invalid project slug`);
  return `${slug}/`;
};
const metaKey = (slug: string) => `${projectPrefix(slug)}meta.json`;
const bookKey = (slug: string) => `${projectPrefix(slug)}book.json`;

/**
 * Normalize an untrusted project-relative path ("assets/ch1/a.png") into a
 * safe key suffix, or null when it escapes ("..", absolute, empty segments).
 */
export function safeRelPath(rel: string): string | null {
  const cleaned = rel.replace(/\\/g, "/").replace(/^\/+/, "");
  if (!cleaned) return null;
  const segments = cleaned.split("/");
  if (segments.some((s) => s === "" || s === "." || s === "..")) return null;
  return segments.join("/");
}

/** A unique, non-reserved slug derived from `name`, deduped against existing. */
export async function uniqueSlug(name: string): Promise<string> {
  const base = baseSlug(name);
  let candidate = base;
  let n = 1;
  const taken = async (slug: string) =>
    (await storage().listKeys(projectPrefix(slug))).length > 0;
  while (RESERVED_SLUGS.has(candidate) || (await taken(candidate))) {
    n += 1;
    candidate = `${base}-${n}`;
  }
  return candidate;
}

/** A minimal starter book for a brand-new project. */
export function defaultBook(name: string): Book {
  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    pageConfig: DEFAULT_PAGE_CONFIG,
    title: name,
    subtitle: "",
    author: "",
    edition: "",
    cover: "",
    chapters: [
      {
        id: "chapter1",
        title: "Chapter 1",
        description: "",
        steps: [
          {
            title: "Step 1",
            instruction: "",
            image: "",
            layout: "single",
            // New projects default to grid layout (rev4 Task 2) — legacy stays
            // available for existing content via the per-step Layout toggle.
            layoutMode: "grid",
            grid: [{ heightFr: 1, cells: [{ widthFr: 1, objects: [] }] }],
          },
        ],
      },
    ],
  };
}

const writeJson = (key: string, value: unknown) =>
  storage().write(key, Buffer.from(JSON.stringify(value, null, 2), "utf8"));

export async function createProject(name: string): Promise<ProjectMeta> {
  await sweepExpired();
  const slug = await uniqueSlug(name);
  const now = Date.now();
  const meta: ProjectMeta = { slug, name, createdAt: now, updatedAt: now };
  await writeJson(metaKey(slug), meta);
  await writeJson(bookKey(slug), defaultBook(name));
  return meta;
}

export async function projectExists(slug: string): Promise<boolean> {
  if (!isValidSlug(slug)) return false;
  return storage().exists(bookKey(slug));
}

/** Permanently delete a project (book, meta, assets — everything). Used by the
 *  homepage "Discard" action; a no-op (not an error) if already gone. */
export async function deleteProject(slug: string): Promise<void> {
  if (!isValidSlug(slug)) return; // nothing valid to delete
  await storage().removePrefix(projectPrefix(slug));
}

/** Create a project at a specific slug from a given book (used to seed /demo). */
export async function seedProject(
  slug: string,
  name: string,
  book: Book,
): Promise<ProjectMeta> {
  const now = Date.now();
  const meta: ProjectMeta = { slug, name, createdAt: now, updatedAt: now };
  await writeJson(metaKey(slug), meta);
  await writeJson(bookKey(slug), book);
  return meta;
}

/**
 * Create a new project from imported files (project-relative paths, e.g.
 * "book.json", "assets/chapter1/x.png"). Writes them under a fresh slug and a
 * fresh meta. Path-traversal guarded. Requires a book.json among the files.
 */
export async function importProject(
  name: string,
  files: { name: string; data: Buffer }[],
): Promise<ProjectMeta> {
  const slug = await uniqueSlug(name);
  const prefix = projectPrefix(slug);

  let hasBook = false;
  for (const f of files) {
    const rel = safeRelPath(f.name);
    if (!rel || rel === "meta.json") continue; // meta is regenerated
    await storage().write(prefix + rel, f.data);
    if (rel === "book.json") hasBook = true;
  }
  if (!hasBook) {
    await storage().removePrefix(prefix);
    throw new Error("archive has no book.json");
  }

  const now = Date.now();
  const meta: ProjectMeta = { slug, name, createdAt: now, updatedAt: now };
  await writeJson(metaKey(slug), meta);
  return meta;
}

/** Store key prefix (chapter scope) for uploaded assets. */
const assetPrefix = (slug: string, chapterId: string) =>
  `${projectPrefix(slug)}assets/${chapterId.replace(/[^a-zA-Z0-9._-]/g, "")}/`;

/** Save an uploaded asset. Caller validates chapterId/filename shape. */
export async function saveAsset(
  slug: string,
  chapterId: string,
  filename: string,
  data: Buffer,
): Promise<void> {
  await storage().write(assetPrefix(slug, chapterId) + filename, data);
}

/** List image filenames already uploaded for a chapter. */
export async function listChapterAssets(
  slug: string,
  chapterId: string,
): Promise<string[]> {
  if (!isValidSlug(slug)) return [];
  const prefix = assetPrefix(slug, chapterId);
  const keys = await storage().listKeys(prefix);
  return keys.map((k) => k.slice(prefix.length)).filter((n) => !n.includes("/"));
}

/**
 * Read a project asset by its path relative to the assets dir, guarding
 * against traversal. Returns the bytes if it exists, else null.
 */
export async function readAsset(
  slug: string,
  rel: string,
): Promise<Buffer | null> {
  if (!isValidSlug(slug)) return null;
  const safe = safeRelPath(rel);
  if (!safe) return null;
  return storage().read(`${projectPrefix(slug)}assets/${safe}`);
}

export async function loadProjectBook(slug: string): Promise<Book> {
  const raw = await storage().read(bookKey(slug));
  if (raw === null) throw new Error(`project ${slug} has no book.json`);
  return migrateBook(JSON.parse(raw.toString("utf8")) as Book);
}

export async function saveProjectBook(slug: string, book: Book): Promise<void> {
  await writeJson(bookKey(slug), book);
  await touch(slug);
}

export async function loadMeta(slug: string): Promise<ProjectMeta | null> {
  try {
    const raw = await storage().read(metaKey(slug));
    return raw === null ? null : (JSON.parse(raw.toString("utf8")) as ProjectMeta);
  } catch {
    return null;
  }
}

/** Bump updatedAt so the project's TTL window resets. */
export async function touch(slug: string): Promise<void> {
  const meta = await loadMeta(slug);
  if (!meta) return;
  meta.updatedAt = Date.now();
  await writeJson(metaKey(slug), meta);
}

export async function listProjects(): Promise<ProjectMeta[]> {
  try {
    const keys = await storage().listKeys("");
    const metaKeys = keys.filter((k) => /^[^/]+\/meta\.json$/.test(k));
    const metas = await Promise.all(
      metaKeys.map((k) => loadMeta(k.slice(0, -"/meta.json".length))),
    );
    return metas
      .filter((m): m is ProjectMeta => m !== null)
      .sort((a, b) => b.updatedAt - a.updatedAt);
  } catch {
    return [];
  }
}

/** Gather every file in a project (relative paths) for download/zip. */
export async function collectProjectFiles(
  slug: string,
): Promise<{ name: string; data: Buffer }[]> {
  if (!isValidSlug(slug)) return [];
  const prefix = projectPrefix(slug);
  const keys = await storage().listKeys(prefix);
  const out: { name: string; data: Buffer }[] = [];
  for (const key of keys) {
    const data = await storage().read(key);
    if (data !== null) out.push({ name: key.slice(prefix.length), data });
  }
  return out;
}

/** Delete projects idle longer than the TTL. Returns the slugs removed. */
export async function sweepExpired(ttlMs = PROJECT_TTL_MS): Promise<string[]> {
  const cutoff = Date.now() - ttlMs;
  const removed: string[] = [];
  for (const meta of await listProjects()) {
    if (meta.updatedAt < cutoff) {
      await deleteProject(meta.slug);
      removed.push(meta.slug);
    }
  }
  return removed;
}
